2020-05-02 18:24:05,407 ERROR: Exception on /like/13 [GET] [in /Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/base.py", line 399, in _entity_descriptor
    return getattr(entity, key)
AttributeError: type object 'Post' has no attribute 'post_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/benliu/PycharmProjects/microblog/app/routes.py", line 163, in like
    post = Post.query.filter_by(post_id=post_id).first()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 1847, in filter_by
    for key, value in kwargs.items()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 1847, in <listcomp>
    for key, value in kwargs.items()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/base.py", line 402, in _entity_descriptor
    "Entity '%s' has no property '%s'" % (description, key)
sqlalchemy.exc.InvalidRequestError: Entity '<class 'app.models.Post'>' has no property 'post_id'
2020-05-02 18:25:11,080 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:53]
2020-05-02 18:26:23,113 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:53]
2020-05-02 18:28:20,595 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:53]
2020-05-02 18:28:25,063 ERROR: Exception on /index [GET] [in /Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/benliu/PycharmProjects/microblog/app/routes.py", line 46, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items, next_url=next_url, prev_url=prev_url, is_liked=is_liked)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/benliu/PycharmProjects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/benliu/PycharmProjects/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/benliu/PycharmProjects/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_post.html' %}
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/benliu/PycharmProjects/microblog/app/templates/_post.html", line 26, in template
    {% if post.post_likers|length == 1 || if post.post_likers|length == 0 %}
jinja2.exceptions.TemplateSyntaxError: expected token 'name', got '|'
2020-05-02 18:29:19,957 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:53]
2020-05-02 18:29:23,418 ERROR: Exception on /index [GET] [in /Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/benliu/PycharmProjects/microblog/app/routes.py", line 46, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items, next_url=next_url, prev_url=prev_url, is_liked=is_liked)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/benliu/PycharmProjects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/benliu/PycharmProjects/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/benliu/PycharmProjects/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_post.html' %}
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/benliu/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/benliu/PycharmProjects/microblog/app/templates/_post.html", line 26, in template
    {% if ( post.post_likers|length == 1 or if post.post_likers|length == 0 ) %}
jinja2.exceptions.TemplateSyntaxError: expected token ')', got 'post'
2020-05-02 18:29:59,593 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:53]
2020-05-02 18:30:37,555 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:53]
2020-05-02 18:31:28,098 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:53]
2020-05-02 18:32:17,856 INFO: Microblog startup [in /Users/benliu/PycharmProjects/microblog/app/__init__.py:53]
